name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install stable
      run: rustup toolchain install stable

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build
      run: ./build.sh && cargo build --all

    - name: Run tests
      run: ./build.sh && cargo test --all

    - name: Build client
      run: ./build.sh

    - name: Build server
      run: ./build.sh && cargo build --release --bin server
